cache:
  directories:
    - ./node_modules
language: node_js
node_js:
  - "8"

install:
  - npm install -g ganache-cli
  - npm install -g truffle
script:
  - ganache-cli -p 8545  > /dev/null &
  - sleep 5
  - truffle test